# Generated by Django 4.2.1 on 2023-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftPartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('material_composition', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('aircraft_model', models.CharField(max_length=100)),
                ('potential_use_cases', models.CharField(max_length=100)),
                ('new_parts_carbon_footprint', models.FloatField()),
                ('recycled_parts_carbon_footprint', models.FloatField()),
                ('water_usage_new_parts', models.FloatField()),
                ('water_usage_recycled_parts', models.FloatField()),
                ('landfill_waste_new_parts', models.FloatField()),
                ('landfill_waste_recycled_parts', models.FloatField()),
                ('energy_consumption_new_parts', models.FloatField()),
                ('energy_consumption_recycled_parts', models.FloatField()),
                ('recycling_rate', models.FloatField()),
                ('toxicity_score_new_parts', models.FloatField()),
                ('toxicity_score_recycled_parts', models.FloatField()),
                ('life_cycle_assessment', models.FloatField()),
                ('renewable_material_content', models.FloatField()),
                ('carbon_footprint_saved', models.FloatField()),
                ('water_usage_saved', models.FloatField()),
                ('landfill_waste_saved', models.FloatField()),
                ('energy_consumption_saved', models.FloatField()),
                ('toxicity_score_difference', models.FloatField()),
                ('remanufacturing_potential', models.FloatField()),
                ('life_cycle_assessment_score', models.FloatField()),
                ('status', models.CharField(default='InUse', max_length=100)),
            ],
        ),
    ]
