# Generated by Django 4.2.1 on 2023-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aircraftpartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftpartdata',
            name='remanufacturing_potential_percent',
            field=models.FloatField(default=1.0),
        ),
    ]
